name: 🐞 Bug Report
description: Report a bug
title: "[BUG]: title"
labels: ["type: bug"]
body:
- type: markdown
  attributes:
    value: |
      ## Thank you for your feedback, pot has become better because of it!
- type: checkboxes
  attributes:
    label: Please confirm the following before submitting a new issue.
    options:
      - label: I have carefully reviewed the official website's usage documentation.
        required: true
      - label: I have searched through the historical issues but could not find an answer.
        required: true
- type: textarea
  attributes:
    label: Description
    description: Simply describe the problem.
  validations:
    required: true
- type: textarea
  attributes:
    label: Reproduction
    description: Steps to reproduce the behaviour.
  validations:
    required: true
- type: dropdown
  attributes:
    label: Platform
    options:
      - Windows
      - Linux
      - MacOS
  validations:
    required: true
- type: textarea
  attributes:
    label: System Version
    description: 'Eg: Windows 11 Home Edition 22621.1702'
  validations:
    required: true
- type: dropdown
  attributes:
    label: Window System(Linux Only)
    options:
      - X11
      - Wayland
- type: textarea
  attributes:
    label: Software Version
- type: textarea
  attributes:
    label: Additional Information
