name: 🌟 Feature Request
description: Suggest an idea
title: "[Feature]: title"
labels: ["type: enhancement"]
body:
- type: markdown
  attributes:
    value: |
      ## Thank you for your feedback, pot has become better because of it!
- type: checkboxes
  attributes:
    label: Please confirm the following before submitting a new issue.
    options:
      - label: I have carefully reviewed the official website's usage documentation.
        required: true
      - label: I have searched through the historical issues but could not find an answer.
        required: true
- type: textarea
  attributes:
    label: Description
    description: Simply describe your idea.
  validations:
    required: true
- type: textarea
  attributes:
    label: Application Scenario
    description: Why is there such a demand?
  validations:
    required: true
- type: textarea
  attributes:
    label: References
    description: Provide implementation ideas or reference documents when necessary.