name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  Code-Review:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: |
          echo Hello OpenAI
          echo Hello Pot
      - uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          OPENAI_API_ENDPOINT: ${{ secrets.OPENAI_ENDPOINT }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LANGUAGE: Chinese
          MODEL: gpt-3.5-turbo
