name: Notify
on:
  issues:
    types: opened
  issue_comment:
    types: created
  pull_request_target:
    types: opened
  discussion_comment:
    types: created

jobs:
  notify:
    name: Notify
    runs-on: ubuntu-latest
    steps:
      # issue
      - uses: colutius/Telegram-Msg@main
        if: github.event_name == 'issue_comment'
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          chatid: ${{ secrets.TELEGRAM_CHATID }}
          button: true
          message: |
            📣 New ${{github.event_name}} in pot-desktop

            💡Title: ${{ github.event.issue.title }}${{ github.event.pull_request.title }}${{ github.event.comment.title }}

            👤User: ${{ github.event.sender.login }}

            ${{ github.event.comment.body }}
          button_name: 👀前往查看👀
          button_url: ${{ github.event.comment.html_url }}
      # discussion
      - uses: colutius/Telegram-Msg@main
        if: github.event_name == 'discussion_comment'
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          chatid: ${{ secrets.TELEGRAM_CHATID }}
          button: true
          message: |
            📣 New ${{github.event_name}} in pot-desktop

            💡Title: ${{ github.event.comment.title }}

            👤User: ${{ github.event.sender.login }}

            ${{ github.event.comment.body }}
          button_name: 👀前往查看👀
          button_url: ${{ github.event.comment.html_url }}
      # issue
      - uses: colutius/Telegram-Msg@main
        if: github.event_name == 'issues'
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          chatid: ${{ secrets.TELEGRAM_CHATID }}
          button: true
          message: |
            📣 New ${{github.event_name}} in pot-desktop

            💡Title: ${{ github.event.issue.title }}

            👤User: ${{ github.event.sender.login }}

            ${{ github.event.issue.body }}
          button_name: 👀前往查看👀
          button_url: https://github.com/${{ github.repository }}/issues
      # pull_request
      - uses: colutius/Telegram-Msg@main
        if: github.event_name == 'pull_request_target'
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          chatid: ${{ secrets.TELEGRAM_CHATID }}
          button: true
          message: |
            📣 New ${{github.event_name}} in pot-desktop

            💡Title: ${{ github.event.pull_request.title }}

            👤User: ${{ github.event.sender.login }}

            ${{ github.event.pull_request.body }}
          button_name: 👀前往查看👀
          button_url: ${{ github.event.pull_request.html_url }}